kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: blue-green-route
  annotations:
    haproxy.router.openshift.io/disable_cookies: 'true'
    haproxy.router.openshift.io/balance: 'roundrobin'
spec:
  to:
    kind: Service
    name: user19-hello-chart-service
    weight: 30
  alternateBackends:
  - kind: Service
    name: user19-chart-app-service
    weight: 70