ReplicaNumber: 1

containers:
  containerPort: 8080
  image: 'quay.io/menachemcohen/image-menachem'
  tag: 'chart_v4'

service:
  servicePort: 8080
  
probes:
  readiness:
    path: /health/readiness # this check the application url path
    initialDelaySeconds: 1 # the time is waiting befor testing the application path
    timeoutSeconds: 1 # the time for timeout
    periodSeconds: 10 # the abount of time to wait between checks
    successThreshold: 1 # count to decalre seccessfull 
    failureThreshold: 3
  liveness:
    path: /health/liveliness # this check the application url path
    initialDelaySeconds: 1 
    timeoutSeconds: 1 # the time for timeout
    periodSeconds: 10 # the abount of time to wait between checks
    successThreshold: 1 # count to decalre seccessfull 
    failureThreshold: 3
volume:
  mount:
    path: /tmp/html
test: Healthy    
github:
  user: Menachem-Cohen
  token: empty-pass
  url: https://api.github.com/repos/Menachem-Cohen/Menachem/issues